# Generated by Django 4.2.5 on 2023-10-05 04:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("anoapp", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
