# Generated by Django 4.2.5 on 2023-10-10 04:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anoapp", "0003_alter_anotherquotationheader_quotation_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anotherquotationheader",
            name="quotation_id",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=10,
                unique=True,
                verbose_name="見積番号",
            ),
        ),
    ]
