# Generated by Django 4.2.5 on 2023-10-05 02:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="opportunity",
            fields=[
                ("CaseID", models.IntegerField(primary_key=True, serialize=False)),
                ("CaseName", models.CharField(max_length=255)),
                ("Representative", models.CharField(max_length=64)),
                ("CustomerName", models.CharField(max_length=128)),
                ("ExpectedOrderDate", models.DateField()),
                ("ExpectedRevenueDate", models.DateField()),
                ("OccurDate", models.DateField()),
                ("CreatedDate", models.DateField()),
                ("Creator", models.CharField(max_length=64)),
                ("UpdatedDate", models.DateField()),
                ("Updater", models.CharField(max_length=64)),
                ("Category", models.CharField(max_length=64)),
            ],
        ),
    ]
