# Generated by Django 4.2.5 on 2023-10-05 02:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                ("No", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ファンタジー", "ファンタジー"),
                            ("文学", "文学"),
                            ("児童文学", "児童文学"),
                            ("SF", "SF"),
                            ("小説", "小説"),
                            ("ミステリー", "ミステリー"),
                            ("ホラー", "ホラー"),
                            ("漫画", "漫画"),
                        ],
                        max_length=20,
                    ),
                ),
                ("author", models.CharField(max_length=100)),
                ("published_date", models.DateField()),
                ("price", models.BigIntegerField()),
                ("stock", models.BooleanField()),
            ],
        ),
    ]
